language: node_js
sudo: false
matrix:
  include:
  - node_js: 4
  - node_js: stable
  - node_js: 4
    env: KARMA=true
  fast_finish: true
env:
  global:
  - secure: oSRLQ1GTkLz5YoJhDxuT5gchx149G0sbfvyEvN8IFl3/mZ/q2K9QVBQtqqD1hhpZ+JrkUWhTN0UDeT3v1hXNr7dyUsy0+zwirvdR52NPSad5wTPOBZS1QRX+JfYTjfuX2ZniX+rc8hBZJlvqKOpqsnpPVpTmUQoFsHCFLejtj2hBRLvhG1B0Pc4ENQ80Mh+tIBOEMgazNNLwyjAkWALEJa61HIKm3TFBggB64bG5/dgEQ6Kldhy9ivzhND5le+g1J4EsPe21FV/Yx9UvVC3onc31R9rUuCrmx+5XsRUkew3KeL9byT2BVg8U7XSaq0PmGDdFYvbaNO8PgNcFLIuCApvsti0tqH/36UDAsyGtuFpHA8/PthLlLSTFBDkdXyH7O/qxty0FyaQUn3PudwrpRhqqbQr/UXlGlHm0Gth3s1nkimJx7kwcms8t0PKwfJYJfrrHxHqkvldv7+ikjL00YUCKpfhx8DGnroQdzcaByoIiLiMrqVkpDl23eK/zeYfJzXPDMcbhUMKTJGn/wBVLZa6jCCSqTTUh7HNmTF4Hdnxx7NpdGH4kaNTtDxfNnBQVUN9umQN8iOEZVBZ7SL7flLcJKamAysBgQ2wdhB7+EjjCCPyTmk78p3g3g3W7Gkr9jBb4HjkgWytUxDOiCQFKOESBNRDflUc6cPM/Bpi1WFg=
  - secure: jijfJkqClLbOLsAnJLpyuA3TijswWTgHUH8v3fN2NhIp9zvRQlrsul6Go19+WDbNm47wJEhN2TcRMrHlhUpDQVtGOtZjLZ7Vnzfbm76ICJkRcZwEUY49N3lvPfWrn4eXtFOzCWR/zEmbMcDWMO7H43mM2QpmsMOjHsthOgzARplJ9afXIWv3L8jS4SuJq52fRK0WRf8jVTUI1K9bc/HKc222bd3wLXDUguvl3T1sggVabJ+IL0NAGbe2mg9ya3FGdwHQGrRvJA+B82AGFpCvPJqXZ10YfHBhdbppDT/pEDtVvClWvfl0PP0UnLwFz2uCF0N9lY6RO7J6Q8y3VDyC17eXN5/MCpdACyV/J5AtLEgV4fkpns32tDSYNIAoQS7Jq8tW9judt3g8GbLrHExZfzdmA9h119/84TsT7TgHP8Wu4E7S4001SVPDLQFeLSrTPfgVvsb9UsfAhVg9hlNRRHy0m3y73NnLjh0r0qDbjR9re/vjw0q40Ao4dMT1gdPNRzI+xkDuirQiYR11lQCfIIXwESID+k/VaaK/rvG4L9i2ZZbSirI5yoIM6qL1zeM5+jjL8wSegsL6Bv/f2BFfpuZAr6HHuyqWy9U6S8WZS8oqsMAtVdQ6w13d+5Uvmpx9Omy7r8s29TNyybQOXr3/b3gRDr4YtgoXb7UEl6Zp6vw=
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: gulp test
after_success:
- cat coverage/*/lcov.info > coveralls.txt
- cat coveralls.txt | node_modules/coveralls/bin/coveralls.js
