language: node_js
matrix:
  include:
    # Node
    - node_js: 4
    - node_js: stable

    # Local Browsers
    - node_js: 4
      env: KARMA=true
  fast_finish: true
sudo: false
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
